### ISSUE TITLE
Unsupported path format

### ISSUE THREAD

**Issue by hohserg1** [dedepete/FreeLauncher#52]
When assets checking:

System.NotSupportedException:
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at FreeLauncher.Forms.LauncherForm.<>c__DisplayClass27_0.<LaunchButton_Click>b__5(Object <sender>, RunWorkerCompletedEventArgs <e>)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by dedepete** [comment]
Please provide some info like an executed game version and full logs w/ enabled debug mode.  
I was unable to reproduce the exception.

**Comment by hohserg1** [comment]
I'm sorry, I use unsupported path to modpack-dir
