### ISSUE TITLE
don't work minecraft 1.18.2-forge-40.1.0

### ISSUE THREAD

**Issue by HamsterKornelius** [dedepete/FreeLauncher#74]
minecraft 1.18.2
forge-40.1.0
no problems without a forge
mods not installed
starting with a forge doesn't start anything

[E] WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-exports
[E] WARNING: Unknown module: cpw.mods.securejarhandler specified to --add-opens
[E] Exception in thread "main" java.lang.module.FindException: Module org.objectweb.asm.commons not found, required by org.openjdk.nashorn
[E] 	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
[E] 	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
[E] 	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
[E] 	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:492)
[E] 	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
[E] 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:137)
[O] 
[E] 

============
//Oops, seems like the game has been exited with unusual error code!
//Printing debug information right now!

FreeLauncher 0.2.4_master.8566073

System info:
  Operating system:
    OSFullName: Майкрософт Windows 10 Pro
    Build: 9200
    Is64BitOperatingSystem: True
  Java path: '' (null-bit)

Process info:
  Minecraft version/type: 1.18.2-forge-40.1.0/release
  Executable file: 'C:\Program Files\Common Files\Oracle\Java\javapath\java.exe'
  Arguments: '-DignoreList=bootstraplauncher,securejarhandler,asm-commons,asm-util,asm-analysis,asm-tree,asm,client-extra,fmlcore,javafmllanguage,mclanguage,forge-,${version_name}.jar -DmergeModules=jna-5.10.0.jar,jna-platform-5.10.0.jar,java-objc-bridge-1.0.0.jar -DlibraryDirectory=${library_directory} -p ${library_directory}/cpw/mods/bootstraplauncher/1.0.0/bootstraplauncher-1.0.0.jar${classpath_separator}${library_directory}/cpw/mods/securejarhandler/1.0.3/securejarhandler-1.0.3.jar${classpath_separator}${library_directory}/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar${classpath_separator}${library_directory}/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar${classpath_separator}${library_directory}/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar${classpath_separator}${library_directory}/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar${classpath_separator}${library_directory}/org/ow2/asm/asm/9.2/asm-9.2.jar --add-modules ALL-MODULE-PATH --add-opens java.base/java.util.jar=cpw.mods.securejarhandler --add-exports java.base/sun.security.util=cpw.mods.securejarhandler --add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump "-Dos.name=Windows 10" -Dos.version=10.0 -Djava.library.path=C:\Users\I7\AppData\Roaming\.minecraft\natives\ -Dminecraft.launcher.brand=FreeLauncher -Dminecraft.launcher.version=0.2.4_master.8566073 -cp C:\Users\I7\AppData\Roaming\.minecraft\libraries\cpw\mods\securejarhandler\1.0.3\securejarhandler-1.0.3.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm\9.2\asm-9.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-commons\9.2\asm-commons-9.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-tree\9.2\asm-tree-9.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-util\9.2\asm-util-9.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\ow2\asm\asm-analysis\9.2\asm-analysis-9.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\net\minecraftforge\accesstransformers\8.0.4\accesstransformers-8.0.4.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\antlr\antlr4-runtime\4.9.1\antlr4-runtime-4.9.1.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\net\minecraftforge\eventbus\5.0.3\eventbus-5.0.3.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\net\minecraftforge\forgespi\4.0.10\forgespi-4.0.10.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\net\minecraftforge\coremods\5.0.1\coremods-5.0.1.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\cpw\mods\modlauncher\9.1.3\modlauncher-9.1.3.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\net\minecraftforge\unsafe\0.2.0\unsafe-0.2.0.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\electronwill\night-config\core\3.6.4\core-3.6.4.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\electronwill\night-config\toml\3.6.4\toml-3.6.4.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\apache\maven\maven-artifact\3.6.3\maven-artifact-3.6.3.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\net\jodah\typetools\0.8.3\typetools-0.8.3.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\net\minecrell\terminalconsoleappender\1.2.0\terminalconsoleappender-1.2.0.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\jline\jline-reader\3.12.1\jline-reader-3.12.1.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\jline\jline-terminal\3.12.1\jline-terminal-3.12.1.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\spongepowered\mixin\0.8.5\mixin-0.8.5.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\openjdk\nashorn\nashorn-core\15.3\nashorn-core-15.3.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\cpw\mods\bootstraplauncher\1.0.0\bootstraplauncher-1.0.0.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlloader\1.18.2-40.1.0\fmlloader-1.18.2-40.1.0.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\mojang\logging\1.0.0\logging-1.0.0.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\mojang\blocklist\1.0.10\blocklist-1.0.10.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\mojang\patchy\2.2.10\patchy-2.2.10.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\github\oshi\oshi-core\5.8.5\oshi-core-5.8.5.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna\5.10.0\jna-5.10.0.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\net\java\dev\jna\jna-platform\5.10.0\jna-platform-5.10.0.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\slf4j\slf4j-api\1.8.0-beta4\slf4j-api-1.8.0-beta4.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-slf4j18-impl\2.17.0\log4j-slf4j18-impl-2.17.0.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\ibm\icu\icu4j\70.1\icu4j-70.1.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\mojang\javabridge\1.2.24\javabridge-1.2.24.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.4\jopt-simple-5.0.4.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\io\netty\netty-all\4.1.68.Final\netty-all-4.1.68.Final.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\google\guava\guava\31.0.1-jre\guava-31.0.1-jre.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\commons-io\commons-io\2.11.0\commons-io-2.11.0.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\commons-codec\commons-codec\1.15\commons-codec-1.15.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\mojang\brigadier\1.0.18\brigadier-1.0.18.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\mojang\datafixerupper\4.1.27\datafixerupper-4.1.27.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\google\code\gson\gson\2.8.9\gson-2.8.9.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\mojang\authlib\3.3.39\authlib-3.3.39.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\apache\commons\commons-compress\1.21\commons-compress-1.21.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.4.14\httpcore-4.4.14.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\it\unimi\dsi\fastutil\8.5.6\fastutil-8.5.6.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.17.0\log4j-api-2.17.0.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.17.0\log4j-core-2.17.0.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.2.2\lwjgl-tinyfd-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-tinyfd\3.2.2\lwjgl-tinyfd-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.12.4\text2speech-1.12.4.jar;C:\Users\I7\AppData\Roaming\.minecraft\libraries\com\mojang\text2speech\1.12.4\text2speech-1.12.4.jar;C:\Users\I7\AppData\Roaming\.minecraft\versions\1.18.2\1.18.2.jar cpw.mods.bootstraplauncher.BootstrapLauncher --launchTarget forgeclient --fml.forgeVersion 40.1.0 --fml.mcVersion 1.18.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20220404.173914 --username DED --version "Ахалай махалай" --gameDir C:\Users\I7\AppData\Roaming\.minecraft\ --assetsDir C:\Users\I7\AppData\Roaming\.minecraft\assets\ --assetIndex 1.18 --uuid sample_token --accessToken sample_token --clientId ${clientid} --xuid ${auth_xuid} --userType offline --versionType release --width 2560 --height 1080'
  Exit code: 1

//Finished printing debug information
============

**Comment by HamsterKornelius** [comment]
I figured out how to fix the library paths, but a new problem awaited me...

[E] Exception in thread "main" java.lang.module.ResolutionException: Module minecraft contains package net.minecraft.obfuscate, module _1._18._2 exports package net.minecraft.obfuscate to minecraft
[E] 	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
[E] 	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:807)
[E] 	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
[E] 	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
[E] 	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
[E] 	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
[E] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
[E] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
[E] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
[E] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
[E] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
[E] 	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
[E] 	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
[O] 
[E]
